#!/usr/bin/env bash
# Hyprland: keybindings, input, autostart and the floating-terminal rule.
#
# Hyprland 0.56+ uses the Lua config format. The distro ships an autogenerated
# ~/.config/hypr/hyprland.lua; we leave that alone and append a require for our
# own custom.lua at the very end, so our settings win over everything above.

step "Hyprland"

HYPR_DIR=$HOME/.config/hypr
MAIN=$HYPR_DIR/hyprland.lua

# Hyprland copies its default config in on first start. A machine that has
# never run it (a headless box, say) has none yet, so seed it the same way.
DEFAULT_MAIN=/usr/share/hypr/hyprland.lua
if [[ ! -f $MAIN && -f $DEFAULT_MAIN ]]; then
  run mkdir -p "$HYPR_DIR"
  run cp "$DEFAULT_MAIN" "$MAIN"
  ok "$(tilde "$MAIN") created from Hyprland's default"
fi
if [[ ! -f $MAIN ]] && (( ! DRY_RUN )); then
  warn "$(tilde "$MAIN") not found — start Hyprland once so it writes a default config, then re-run."
  return 0 2>/dev/null || exit 0
fi

link config/hypr/custom.lua "$HYPR_DIR/custom.lua"

# Machine-specific display layout: copied, not linked, so each machine can differ.
copy config/hypr/monitors.lua.example "$HYPR_DIR/monitors.lua"

ensure_line "$MAIN" \
  '-- Personal overrides, loaded last so they win over everything above.
require("custom")' \
  '^\s*require\("custom"\)'

if need_cmd hyprctl && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
  run hyprctl reload >/dev/null 2>&1 || true
  errs=$(hyprctl configerrors 2>/dev/null | tr -d '[:space:]')
  if [[ -n $errs ]]; then
    warn "hyprctl reported config errors:"
    hyprctl configerrors
  else
    ok "config reloaded, no errors"
  fi
else
  skip "Hyprland not running — config applies at next login"
fi
