#!/usr/bin/env bash
# kitty: follow the DMS theme, and Ctrl+Up / Ctrl+Down for font size.
#
# kitty.conf is not replaced wholesale — it's a file people keep tweaking.
# We only ensure the two things we care about are present.

step "kitty"

KITTY=$HOME/.config/kitty/kitty.conf

if [[ ! -f $KITTY ]]; then
  skip "no $(tilde "$KITTY"), nothing to patch"
  return 0 2>/dev/null || exit 0
fi

# DankMaterialShell regenerates dank-theme.conf on every theme change.
if [[ -f $HOME/.config/kitty/dank-theme.conf ]]; then
  ensure_line "$KITTY" \
    '# Colours, regenerated by DankMaterialShell whenever the theme changes.
include ./dank-theme.conf' \
    '^\s*include\s+\./dank-theme\.conf'
else
  skip "dank-theme.conf not generated yet (run DMS once)"
fi

ensure_line "$KITTY" \
  '# Font size
map ctrl+up    change_font_size all +1.0
map ctrl+down  change_font_size all -1.0
map ctrl+0     change_font_size all 0' \
  '^\s*map\s+ctrl\+up\s+change_font_size'

if (( ! DRY_RUN )) && pgrep -x kitty >/dev/null 2>&1; then
  pkill -USR1 -x kitty && ok "reloaded running kitty instances"
fi
