-- ============================================================
--  custom.lua — personal overrides, loaded last from hyprland.lua
--  Keep your edits here so the autogenerated hyprland.lua stays clean.
-- ============================================================

local mainMod = "SUPER"

-- DankMaterialShell's generated Hyprland integration (bar blur/xray + its
-- preferred gaps and rounding). Comment this out if you'd rather keep your own
-- look-and-feel; anything set below this line still wins.
-- pcall: DMS writes this file on first run, so it won't exist on a fresh install.
pcall(require, "dms.layout")

-- Per-machine display layout. Not every machine has the same outputs, so this
-- lives in its own file and is optional.
pcall(require, "monitors")


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- DankMaterialShell (Quickshell topbar + notifications + control center)
    hl.exec_cmd("dms run")
    -- qsl: Quickshell launcher with package install/uninstall (~/.config/quickshell/launcher)
    hl.exec_cmd("qs -c launcher")
end)


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        -- Swiss German. The default (empty) variant of "ch" is German (Switzerland),
        -- with dead keys for ^ ` ´. Use "de_nodeadkeys" if you'd rather type those
        -- accents directly, or "de_mac" for Apple keyboards.
        kb_layout  = "ch",
        kb_variant = "",
    },
})


------------------
---- BEHAVIOR ----
------------------

hl.config({
    binds = {
        -- When a directional window move hits the edge of the monitor,
        -- throw the window onto the neighbouring monitor instead of no-op.
        window_direction_monitor_fallback = true,
    },
})


----------------
---- APPS -----
----------------

local terminal     = "foot"
local fileManager  = "dolphin"
local browser      = "firefox"

hl.bind(mainMod .. " + W",          hl.dsp.window.close(),        { description = "Close window" })
hl.bind(mainMod .. " + F",          hl.dsp.window.fullscreen(),   { description = "Fullscreen" })
hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.window.fullscreen({ mode = 1 }),
    { description = "Maximize (keeps bar and gaps)" })
hl.bind(mainMod .. " + Return",     hl.dsp.exec_cmd(terminal),    { description = "Terminal"     })
hl.bind(mainMod .. " + SHIFT + F",  hl.dsp.exec_cmd(fileManager), { description = "File manager" })
hl.bind(mainMod .. " + SHIFT + B",  hl.dsp.exec_cmd(browser),     { description = "Browser"      })
hl.bind(mainMod .. " + SHIFT + O",  hl.dsp.exec_cmd("obsidian"),  { description = "Obsidian"     })


-------------------
---- SESSION ------
-------------------

-- The stock config quits Hyprland on a bare SUPER + M, which is easy to hit by
-- accident. Move it behind SHIFT.
hl.unbind(mainMod .. " + M")
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit(), { description = "Quit Hyprland" })


------------------
---- LAUNCHER ----
------------------

-- anarchy: the Quickshell menu-launcher. Opens on a root menu (Apps, Capture,
-- Install, Remove, Style, Setup, Update, System) rather than a list of apps.
hl.bind(mainMod .. " + Space",     hl.dsp.exec_cmd("qs -c launcher ipc call launcher toggle"),
    { description = "Anarchy menu" })
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("qs -c launcher ipc call launcher install"),
    { description = "Install a package" })
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("qs -c launcher ipc call launcher capture"),
    { description = "Capture menu" })
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("qs -c launcher ipc call launcher wallpaper"),
    { description = "Wallpaper picker" })
-- `go <screen>` opens any menu directly: root, apps, capture, managers, remove,
-- style, theme, wallpaper, setup, update, system.
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("qs -c launcher ipc call launcher go system"),
    { description = "Power menu" })

-- Window switcher: DankMaterialShell's overview.
hl.bind(mainMod .. " + Tab", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"),
    { description = "Window overview" })


------------------
---- CAPTURE ----
------------------

-- Print: select an area, straight to the clipboard.
hl.bind("Print",                  hl.dsp.exec_cmd("qsl-capture screenshot-region-copy"),
    { description = "Screenshot area to clipboard" })
-- Shift+Print also writes a PNG to ~/Pictures/Screenshots.
hl.bind("SHIFT + Print",          hl.dsp.exec_cmd("qsl-capture screenshot-region"),
    { description = "Screenshot area, copy and save" })
hl.bind(mainMod .. " + Print",    hl.dsp.exec_cmd("qsl-capture screenshot-screen"),
    { description = "Screenshot whole screen" })
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("qsl-capture record-region-audio"),
    { description = "Record region with audio (again to stop)" })


-----------------------------
---- FLOATING TERMINAL ------
-----------------------------

-- qsl hands package installs and removals to a terminal with this class so
-- pacman can ask for a password and show progress.
hl.window_rule({
    name  = "float-qsl-term",
    match = { class = "^qsl-term$" },
    float = true,
    size  = "1100 720",
    center = true,
})


---------------------------
---- VIM-KEY NAVIGATION ----
---------------------------

-- SUPER + J is bound to `togglesplit` by the stock config. Free it up first.
hl.unbind(mainMod .. " + J")
hl.bind(mainMod .. " + T", hl.dsp.layout("togglesplit"),
    { description = "Toggle split direction (dwindle)" })

-- Move focus:            SUPER + h / j / k / l
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left"  }), { description = "Focus left"  })
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down"  }), { description = "Focus down"  })
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up"    }), { description = "Focus up"    })
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }), { description = "Focus right" })

-- Move the window:       SUPER + SHIFT + h / j / k / l
-- Thanks to window_direction_monitor_fallback above, pushing a window past the
-- edge of a monitor moves it to the adjacent monitor.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }), { description = "Move window left"  })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }), { description = "Move window down"  })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }), { description = "Move window up"    })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }), { description = "Move window right" })


------------------------------
---- MONITORS (SCREEN HOP) ----
------------------------------

-- Jump focus between screens:   SUPER + CTRL + h / l
hl.bind(mainMod .. " + CONTROL + H", hl.dsp.focus({ monitor = "-1" }), { description = "Focus previous monitor" })
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.focus({ monitor = "+1" }), { description = "Focus next monitor"     })

-- Send the window to another screen:  SUPER + CTRL + SHIFT + h / l
hl.bind(mainMod .. " + CONTROL + SHIFT + H", hl.dsp.window.move({ monitor = "-1" }), { description = "Move window to previous monitor" })
hl.bind(mainMod .. " + CONTROL + SHIFT + L", hl.dsp.window.move({ monitor = "+1" }), { description = "Move window to next monitor"     })


-----------------
---- RESIZE -----
-----------------

-- SUPER + ALT + h/j/k/l resizes the focused window, vim-style.
hl.bind(mainMod .. " + ALT + H", hl.dsp.window.resize({ x = -60, y =   0 }), { description = "Shrink width",  repeating = true })
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.resize({ x =  60, y =   0 }), { description = "Grow width",    repeating = true })
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.resize({ x =   0, y = -60 }), { description = "Shrink height", repeating = true })
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.resize({ x =   0, y =  60 }), { description = "Grow height",   repeating = true })
