-- anarchy headless: ignore the machine's own screens.
--
-- Installed by installer-headless-rdp.sh; custom.lua loads it when present.
--
-- A monitor plugged into the machine joins the session as a real output, takes
-- workspace 1 and the focus, and then windows open where no RDP client can see
-- them. Worse, with every user running their own seatless Hyprland there is no
-- seat to decide who owns that screen, so the sessions fight over it.
--
-- The catch-all rule below disables any output not named explicitly. The RDP
-- screens are named when they are created — hypr-rdp's own "hypr-rdp", and
-- "ANARCHY-RDP-n" in fixed mode — and an explicit rule beats the catch-all, so
-- they stay enabled.
--
-- To use a screen attached to the machine after all, remove the link at
-- ~/.config/hypr/headless.lua and run: hyprctl reload
hl.monitor({ output = "", disabled = true })
