theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline="multiple"
cursorline=true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
0 = "goto_line_start"
'$' = "goto_line_end"
